# The default app title
title : 'Boame web application'
# Seo Keywords
keywords : 'Moorexa, Moorexa PHP framework'
# Seo Description
description : 'The best PHP framework out there, with so much power and flexibility'
# Seo Author
author : 'Ifeanyi Amadi, Amadiify'
# Favicon
icon : 'favicon.png'
# Beautiful url
beautiful_url_target : __app_request__
# Router global configuration
router :
  # set default controller and view
  default :
    controller : 'app'
    view : 'home'
# launcher configuration
launcher :
  # set the content types for each platforms
  contentType :
    api : 'application/json'
    web : 'text/html'
    cli : 'text/plain'
# actions for model
actions :
  - add
  - create
  - edit
  - delete
  - show
# external socket address
socketAddress : 'http://beta.wekiwork.com:8083'